export const CREATE_DELIVERY_REQUEST = "CREATE_DELIVERY_REQUEST";
export const CREATE_DELIVERY_SUCCESS = "CREATE_DELIVERY_SUCCESS";
export const CREATE_DELIVERY_FAIL = "CREATE_DELIVERY_FAIL";

export const DELIVERY_GET_BY_ID_REQUEST = "DELIVERY_GET_BY_ID_REQUEST";
export const DELIVERY_GET_BY_ID_SUCCESS = "DELIVERY_GET_BY_ID_SUCCESS";
export const DELIVERY_GET_BY_ID_FAIL = "DELIVERY_GET_BY_ID_FAIL";

export const UPDATE_DELIVERY_REQUEST = "UPDATE_DELIVERY_REQUEST";
export const UPDATE_DELIVERY_SUCCESS = "UPDATE_DELIVERY_SUCCESS";
export const UPDATE_DELIVERY_FAIL = "UPDATE_DELIVERY_FAIL";

export const DELIVERY_EACH_GET_REQUEST = " DELIVERY_EACH_GET_REQUEST";
export const DELIVERY_EACH_GET_SUCCESS = "DELIVERY_EACH_GET_SUCCESS";
export const DELIVERY_EACH_GET_FAIL = "DELIVERY_EACH_GET_FAIL";


